Vehicles.Web/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Vehicles.Web.Models
{
    public class Customer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string AddressLn1 { get; set; }
        public string AddressLn2 { get; set; }
        public string AddressLn3 { get; set; }
        public string Phone { get; set; }
        public IEnumerable<Vehicle> Vehicles { get; set; }
    }
}

Vehicles.Web/Models/Page{T}.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Vehicles.Web.Models
{
    public sealed class Page<T>
    {
        public IEnumerable<T> Items { get; set; }

        public long TotalSize { get; set; }
    }
}

Vehicles.Web/Models/ReportViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace Vehicles.Web.Models
{
    public class ReportViewModel
    {
        public List<JqueryReportHeader> Headers;

        public List<Dictionary<string, object>> Data { get; set; }
    }

    public class JqueryReportHeader
    {
        // Must be named "data" for the JQuery datatable to understand the column name
        public string data { get; set; }

        // Must be named "bSearchable" for the JQuery datatable to understand which columns will be searhable
        public bool bSearchable { get; set; }

        public JqueryReportHeader(string header)
        {
            data = header;
            bSearchable = true;
        }
    }
}

Vehicles.Web/Models/SearchViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace Vehicles.Web.Models
{
    public class SearchViewModel
    {
        public SearchViewModel()
        {
        }

        [Description("CustomerName")]
        public string CustomerName { get; set; }

        [Description("Status")]
        public string Status { get; set; }
    }
}

Vehicles.Web/Models/UrlModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Vehicles.Web.Models
{
    public class UrlModel
    {
        public string Url { get; set; }
    }
}

Vehicles.Web/Models/Vehicle.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Vehicles.Web.Models
{
    public class Vehicle
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string VIN { get; set; }
        public string RegNo { get; set; }
        public DateTime LastPingTime { get; set; }
        public bool IsActive { get; set; }
    }
}

Vehicles.Web/Models/VehiclesStatusModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Vehicles.Web.Models
{
    public class VehiclesStatusModel
    {
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string VIN { get; set; }
        public string RegNo { get; set; }
        public DateTime LastPingTime { get; set; }
        public bool IsActive { get; set; }
    }
}

Vehicles.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Vehicles.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Vehicles.Web/Controllers/VehiclesStatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Vehicles.Web.Models;
using Vehicles.Web.Helpers;
using System.Net.Http;
using Microsoft.Extensions.Options;
using System.Net;
using System.IO;

namespace Vehicles.Web.Controllers
{
    public class VehiclesStatusController : Controller
    {
        private UrlModel _urlModel;
        public VehiclesStatusController(IOptions<UrlModel> urlModel)
        {
            _urlModel = urlModel.Value;
        }
        [ActionName("ViewReport")]
        public IActionResult VehiclesStatus()
        {
            return Initialize("~/Views/Home/VehicleStatus.cshtml");
        }
        public IActionResult Initialize(string viewPath)
        {
            var viewModel = new SearchViewModel();

            return View(viewPath, viewModel);
        }
        public IActionResult Search(SearchViewModel model)
        {
            var result = DoSearch(model).Result;
            return PartialView("ReportGrid", result.Headers);
        }
        public ActionResult GetSearchResult()
        {
            var gridViewModel = (ReportViewModel)TempData.Get<ReportViewModel>("gridViewModel");
            return Json(new { resources = (gridViewModel!=null)?gridViewModel.Data:null, Columns = (gridViewModel != null) ? gridViewModel.Headers:null });
        }
        public async Task<ReportViewModel> DoSearch(SearchViewModel model)
        {
            string url = string.Empty;
            url = _urlModel.Url + "customers/name?";
            //if(model.CustomerName!= null && model.CustomerName!= string.Empty)
            //    url += "name =" + model.CustomerName ;
            //if (model.Status != null && model.Status != string.Empty)
            //    url += "&vehicleStatus=" + model.Status;
            url += "name=" + ((model.CustomerName==null)?string.Empty:model.CustomerName);
            url += "&vehicleStatus=" + ((model.Status == null) ? string.Empty : model.Status);

            var req = WebRequest.Create(url);
            var r = await req.GetResponseAsync().ConfigureAwait(false);

            var responseReader = new StreamReader(r.GetResponseStream());
            var responseData = await responseReader.ReadToEndAsync();

            var lstCustomers = Newtonsoft.Json.JsonConvert.DeserializeObject<Page<Customer>>(responseData).Items;

            var gridViewModel = new ReportViewModel
            {
                Data = ModelParser.GetCustomersRows(lstCustomers),
                Headers = ModelParser.GetCustomersHeaders(lstCustomers)
            };

            TempData.Put("gridViewModel", gridViewModel);
            return gridViewModel;
        }
    }
}

Vehicles.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Vehicles.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Vehicles.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run & Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Vehicles.Web/Views/Home/VehicleStatus.cshtml
@using Vehicles.Web.Models
@model SearchViewModel
@{
    ViewData["Title"] = "Vehicles Status";
}
<div>
    @using (Html.BeginForm("Search", "VehiclesStatus", FormMethod.Post))
    {
        @Html.Partial("SearchPanel", Model);
    }
</div>

<div id="searchResults"></div>

@section scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            InitializeReport("VehiclesStatus","CustomerName");
        });
    </script>

    @* Bootstrap multiselet*@
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="~/js/jquery-ui.js"></script>
    <script src="~/js/bootstrap-multiselect.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="~/css/bootstrap-multiselect.css">

    @* Jquery datatable*@
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />

    @* Jquery fixedcolumns*@
    <script src="https://cdn.datatables.net/fixedcolumns/3.2.3/js/dataTables.fixedColumns.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/fixedcolumns/3.2.3/css/fixedColumns.dataTables.min.css" />

    @* Jquery export and print buttons*@
    <script src="https://cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>
    <script src="//cdn.datatables.net/buttons/1.4.2/js/buttons.flash.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
    <script src="//cdn.datatables.net/buttons/1.4.2/js/buttons.html5.min.js"></script>
    <script src="//cdn.datatables.net/buttons/1.4.2/js/buttons.print.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.4.2/css/buttons.dataTables.min.css" />

    @*Datatabl semantic style *@
    <link href="~/css/Semantic-UI-CSS/semantic.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/dataTables.semanticui.min.css" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.semanticui.min.js"></script>

    @* Row group extension*@
    <script src="https://cdn.rawgit.com/ashl1/datatables-rowsgroup/v1.0.1/dataTables.rowsGroup.js"></script>

    @*Report style*@
    <link href="~/css/Report.css" rel="stylesheet" />

    <script src="~/js/SearchManager.js"></script>
}


Vehicles.Web/Views/Shared/ReportGrid.cshtml
@using Vehicles.Web.Models;
@model List<JqueryReportHeader>

<head>
    <style>
        th, td {
            white-space: nowrap;
        }

        div.dataTables_wrapper {
            /*width: 800px;*/
            height: 100%;
            margin: 0 auto;
        }
    </style>
</head>
<table id="reportGrid" class="ui celled table " cellspacing="0" style="width:100%">
    <thead>
        <tr>
            @foreach (JqueryReportHeader colName in Model)
            {
                <th>@colName.data</th>
            }
        </tr>
    </thead>
</table>

Vehicles.Web/Views/Shared/SearchPanel.cshtml
@using Vehicles.Web.Models
@model SearchViewModel
<div class="panel panel-default" style="text-align:center;margin-top:10px;margin-bottom:10px">
    <div class="row" style="margin:5px 5px 5px">
        <div class="col-md-2" style="margin-top: 7px;">
            @Html.LabelFor(model => Model.CustomerName)
        </div>
        <div class="col-md-4">
            @Html.TextBoxFor(model => Model.CustomerName, new { @id = "CustomerName", @class = "form-control" })
        </div>
        <div class="col-md-1" style="text-align:right;margin-top: 7px">
            @Html.LabelFor(model => Model.Status)
        </div>
        <div class="col-md-2">
            @Html.DropDownListFor(Model => Model.Status, new SelectList(new List<string> { "Active", "InActive"}), "Select All", new { @class = "form-control", @id = "drp_status" })
        </div>
        <div class="col-md-1" style="float:right;margin-right:25px">
            <button id="search" type="button" class="btn btn-primary"><i style="padding:1px" id="searchSpinner"></i>Search</button>
        </div>
    </div>
</div>

Vehicles.Web/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vehicles.Web</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Vehicles.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li>@Html.ActionLink("VehiclesStatus", "ViewReport", "VehiclesStatus")</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Vehicles.Web</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>